// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwHOTr2U1UNAOoaQcqbGMUYFDgxhZxqbM',
    appId: '1:377176754434:web:a58b326706cc0314de1a1b',
    messagingSenderId: '377176754434',
    projectId: 'sehety-6e7bf',
    authDomain: 'sehety-6e7bf.firebaseapp.com',
    storageBucket: 'sehety-6e7bf.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFulRU2FkrJygc4juaf_Ac_XCH4CHk9UU',
    appId: '1:377176754434:android:23a826ed6044a0b5de1a1b',
    messagingSenderId: '377176754434',
    projectId: 'sehety-6e7bf',
    storageBucket: 'sehety-6e7bf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSBQM8ES8x2mjHt4NNoZKjgGd7FGmb4Z0',
    appId: '1:377176754434:ios:427d6ab210c7dfb4de1a1b',
    messagingSenderId: '377176754434',
    projectId: 'sehety-6e7bf',
    storageBucket: 'sehety-6e7bf.firebasestorage.app',
    iosBundleId: 'com.example.sehety',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSBQM8ES8x2mjHt4NNoZKjgGd7FGmb4Z0',
    appId: '1:377176754434:ios:427d6ab210c7dfb4de1a1b',
    messagingSenderId: '377176754434',
    projectId: 'sehety-6e7bf',
    storageBucket: 'sehety-6e7bf.firebasestorage.app',
    iosBundleId: 'com.example.sehety',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBwHOTr2U1UNAOoaQcqbGMUYFDgxhZxqbM',
    appId: '1:377176754434:web:cf67039ae6a9b11cde1a1b',
    messagingSenderId: '377176754434',
    projectId: 'sehety-6e7bf',
    authDomain: 'sehety-6e7bf.firebaseapp.com',
    storageBucket: 'sehety-6e7bf.firebasestorage.app',
  );
}
